### ISSUE TITLE
angrop.errors.RopException: Couldn't set registers :(

### ISSUE THREAD

**Issue by thiagopeixoto** [salls/angrop#4]
Hi,

I am running angrop, using the following script 
```python
import angr, angrop

p = angr.Project('rop')
rop = p.analyses.ROP()
rop.find_gadgets()
chain = rop.set_regs(eax=0x4)
chain.print_payload_code()
```
and i am getting this error:
**angrop.errors.RopException: Couldn't set registers :(**

If i try to write to memory,
```python
chain = rop.write_to_mem(0x5655701c, "Hello\0")
```
i also get this error:
**angrop.errors.RopException: No bytes in memory for block starting at 0x41414141.**

Am i doing anything wrong?

Thank you very much!

**Comment by salls** [comment]
Hi,

The error **angrop.errors.RopException: Couldn't set registers :(** will show up whenever angrop can't find a gadget chain to set the requested registers. In small binaries, a gadget that sets eax might not exist.

The second error **angrop.errors.RopException: No bytes in memory for block starting at 0x41414141** sounds like an actual bug. Could you pull the latest angrop and if the error still occurs post the traceback or provide the binary  you are testing on?

**Comment by thiagopeixoto** [comment]
Hi,

I did git pull and i got this message:
**angrop.errors.RopException: Couldnt set registers for any memory write gadget**

It seems the problem is solved. :)

Thank you, salls!
